
trigger:
  - master

variables:
  VERBOSITY: diagnostic
  API_TOOLS_VERSION: 1.0.2-preview.5

strategy:
  matrix:
    macos:
      imageName: 'Hosted macOS'
      MONO_VERSION: 5_18_1
      XCODE_VERSION: 10.3
    windows:
      imageName: 'Hosted Windows 2019 with VS2019'

pool:
  name: $(imageName)

steps:
  - bash: sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh $(MONO_VERSION)
    displayName: 'Switch to the latest Xamarin SDK'
    condition: eq(variables['System.JobName'], 'macos')
  - bash: echo '##vso[task.setvariable variable=MD_APPLE_SDK_ROOT;]'/Applications/Xcode_$(XCODE_VERSION).app;sudo xcode-select --switch /Applications/Xcode_$(XCODE_VERSION).app/Contents/Developer
    displayName: 'Switch to the latest Xcode'
    condition: eq(variables['System.JobName'], 'macos')
  - bash: echo '##vso[task.setvariable variable=PATH;]'$PATH:$HOME/.dotnet/tools
    displayName: 'Add ~/.dotnet/tools to the PATH environment variable'
    condition: eq(variables['System.JobName'], 'macos')

  - task: UseDotNet@2
    displayName: 'Use .NET Core 2.2 SDK'
    inputs:
      version: 2.2.x
  - powershell: dotnet tool install -g api-tools --version $(API_TOOLS_VERSION)
    displayName: 'Install api-tools'

  - powershell: .\build.ps1 --verbosity=$(VERBOSITY)
    displayName: 'Run build'

  - powershell: |
      if (Get-ChildItem output -Filter *.nupkg) {
        api-tools nuget-diff output --latest --group-ids --output output/api-diff --cache externals/package_cache
      }
    displayName: 'API diff'
  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifacts'
    inputs:
      PathToPublish: output
      ArtifactName: nuget
