
trigger:
  - master
  - previous/*

variables:
  VERBOSITY: normal
  API_TOOLS_VERSION: 1.3.1
  CAKE_VERSION: 0.37.0
  DOTNET_CORE_VERSION: 3.0.x
  BOOTS_VERSION: 1.0.2.421

strategy:
  matrix:
    macos:
      imageName: 'Hosted macOS'
      MONO_VERSION: 6_4_0
      XCODE_VERSION: 11
      XAMARIN_ANDROID_VERSION: d16-5-macos
    windows:
      imageName: 'Hosted Windows 2019 with VS2019'
      XAMARIN_ANDROID_VERSION: d16-5-windows

pool:
  name: $(imageName)

steps:
  - bash: sudo $(Agent.HomeDirectory)/scripts/select-xamarin-sdk.sh $(MONO_VERSION)
    displayName: 'Switch to the latest Xamarin SDK'
    condition: eq(variables['System.JobName'], 'macos')
  - bash: echo '##vso[task.setvariable variable=MD_APPLE_SDK_ROOT;]'/Applications/Xcode_$(XCODE_VERSION).app;sudo xcode-select --switch /Applications/Xcode_$(XCODE_VERSION).app/Contents/Developer
    displayName: 'Switch to the latest Xcode'
    condition: eq(variables['System.JobName'], 'macos')
  - bash: echo '##vso[task.setvariable variable=PATH;]'$PATH:$HOME/.dotnet/tools
    displayName: 'Add ~/.dotnet/tools to the PATH environment variable'
    condition: eq(variables['System.JobName'], 'macos')

  - task: InstallAppleCertificate@2
    displayName: Install the iOS certificate
    condition: eq(variables['System.JobName'], 'macos')
    inputs:
      certSecureFile: 'Components iOS Certificate.p12'
  - task: InstallAppleProvisioningProfile@1
    displayName: Install the iOS provisioning profile
    condition: eq(variables['System.JobName'], 'macos')
    inputs:
      provProfileSecureFile: 'Components iOS Provisioning.mobileprovision'
  - task: InstallAppleCertificate@2
    displayName: Install the macOS certificate
    condition: eq(variables['System.JobName'], 'macos')
    inputs:
      certSecureFile: 'Components Mac Certificate.p12'
  - task: InstallAppleProvisioningProfile@1
    displayName: Install the macOS provisioning profile
    condition: eq(variables['System.JobName'], 'macos')
    inputs:
      provProfileSecureFile: 'Components Mac Provisioning.provisionprofile'
  - task: InstallAppleProvisioningProfile@1
    displayName: Install the tvOS provisioning profile
    condition: eq(variables['System.JobName'], 'macos')
    inputs:
      provProfileSecureFile: 'Components tvOS Provisioning.mobileprovision'

  - task: UseDotNet@2
    displayName: 'Use the correct version of the .NET Core SDK'
    inputs:
      version: $(DOTNET_CORE_VERSION)
  - pwsh: |
      dotnet tool install -g cake.tool --version $(CAKE_VERSION)
      dotnet tool install -g api-tools --version $(API_TOOLS_VERSION)
      dotnet tool install -g boots --version $(BOOTS_VERSION)
    displayName: 'Install .NET Core tools'

  - pwsh: boots https://aka.ms/xamarin-android-commercial-$(XAMARIN_ANDROID_VERSION)
    displayName: 'Install the latest version of Xamarin.Android'

  - pwsh: dotnet cake --verbosity=$(VERBOSITY)
    displayName: 'Run build'
    env:
      JavaSdkDirectory: $(JAVA_HOME)

  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifacts'
    inputs:
      PathToPublish: output
      ArtifactName: nuget-$(System.JobName)
